/**:
  ntrip_client_node:
    ros__parameters:
      server:
        host: ntrip.hi-rtk.io
        port: 2101
        mountpoint: SNS_AUTO
        ntrip_version: 'NTRIP/2.0'
      auth:
        enable: True
        username: sns7
        password: "1234"
      ssl:
        enable: false
        cert: ""
        key: ""
        ca_cert: ""
      nmea:
        send_min_interval_seconds: 1.0
        min_length: 3
        max_length: 200
      reconnect:
        initial_seconds: 1.0
        max_seconds: 30.0
        rtcm_timeout_seconds: 4.0
      rtcm:
        frame_id: gnss
        qos_depth: 50
      diagnostics:
        rate: 1.0
      verbose: false
