/**:
  ntrip_client_node:
    ros__parameters:
      auth:
        enable: true
        password: ''
        username: ''
      diagnostics:
        rate: 1.0
      nmea:
        max_length: 200
        min_length: 3
        send_min_interval_seconds: 1.0
      reconnect:
        initial_seconds: 5.0
        max_seconds: 10.0
        rtcm_timeout_seconds: 15.0
      rtcm:
        frame_id: gnss
        qos_depth: 50
      server:
        host: ''
        mountpoint: SNS_AUTO
        ntrip_version: NTRIP/2.0
        port: 2101
      ssl:
        ca_cert: ''
        cert: ''
        enable: false
        key: ''
      verbose: false
