/**:
  um982_node:
    ros__parameters:

      port:
        gnss: /dev/MB-UM982
        gnss_baudrate: 115200
        rtcm: /dev/MB-UM982-RTCM
        rtcm_baudrate: 115200

      heading_offset_deg: -90.0
      heading_length_m: 0.725
      heading_system: 'enu'
      frame_id: 'gps'

      publish:
        nmea: true

      reconnect:
        interval: 2.0

      diagnostics:
        rate: 1.0
        message_timeout: 2.0

      verbose: false
